# This is the main configuration file for the Brigade Kafka chart.
# To override values here, specify them in your own YAML file, and override
# during install or upgrade:
#
#    $ helm install -n brigade-kafka-gateway -f myValues.yaml ./chart
#
# By default, the chart will install without RBAC. To install with
# RBAC, set `rbac.enabled` to `true`.

# kafka is the kafka gateway.

rbac:
  enabled: true
serviceAccount:
  create: true

registry: derekm95
name: brigade-kafka-gateway
tag: 'v0.0.1-alpha.4'
pullPolicy: IfNotPresent

kafka_host: ''
kafka_port: '9092'
kafka_topic: ''
kafka_offset: 'latest'
brigade_project_name: ''
