{{ $fullname := include "kafka-brigade-gateway.fullname" . }}
{{ $serviceAccount := default $fullname .Values.serviceAccount.name }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    app: {{ $fullname }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    role: gateway
    type: kafka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ $fullname }}
        role: gateway
        type: kafka
    spec:
      serviceAccountName: {{ $serviceAccount }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.registry }}/{{ .Values.name }}:{{ default .Chart.AppVersion .Values.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.pullPolicy }}
        env:
          - name: BRIGADE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: BRIGADE_KAFKA_GATEWAY_PORT
            value: {{ .Values.kafka_port | quote }}
          - name: BRIGADE_KAFKA_GATEWAY_TOPIC
            value: {{ .Values.kafka_topic | quote }}
          - name: BRIGADE_KAFKA_GATEWAY_HOST
            value: {{ .Values.kafka_host | quote }}
          - name: BRIGADE_KAFKA_GATEWAY_OFFSET
            value: {{ .Values.kafka_offset | quote }}
          - name: BRIGADE_KAFKA_GATEWAY_BRIGADE_PROJECT_NAME
            value: {{ .Values.brigade_project_name | quote }}
